version: '3.3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      -  /var/lib/mysql/
    environment:
      - MYSQL_DATABASE=agenda-petshop
      - MYSQL_USER='root'
      - MYSQL_ROOT_PASSWORD=adm123
      - MYSQL_PASSWORD='password'
  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 5000:80
    environment:
      - PMA_ARBITRARY=1
  web: 
    build: .
    links: 
      - db
    volumes:
      - ./:/app
    ports: [
      "3000:3000"
    ]
    depends_on:
      - db
    